import type { Destination } from "./types";

// Scores (repos/exploration/gastronomie/nature_plage/effervescence_urbaine/rythme) migrés
// mécaniquement depuis l'ancien modèle émotions/vibe le 23/08/2026 :
// repos = moy(deconnexion, lacher_prise) ; exploration = moy(emerveillement, inspiration) ;
// gastronomie = ancien gourmandise ; nature_plage = ancien nature ;
// effervescence_urbaine = ancien densite_urbaine ; rythme = ancien pression_horaire.
// duration/budget : première passe de Claude, à valider par Soumia comme les précédentes.
export const DESTINATIONS: Destination[] = [
  {
    id: "italie-nord-culture",
    title: "Italie : Florence, Rome & Pise",
    authenticity_badge: "tested_approved",
    content_slug: "italie",
    summary:
      "Les trésors de la Renaissance, l'histoire romaine et les ruelles animées de la Toscane au Latium.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/italie/web-IMG_20260723_201932.jpg",
    filters: {
      distance: ["europe"],
      climate: ["chaleur", "douceur"],
      transport: ["transports_possibles"],
      sport_level: ["actif"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["confort", "premium"],
    },
    scores: { repos: 3, exploration: 5, gastronomie: 5, nature_plage: 2, effervescence_urbaine: 4, rythme: 4 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["GrandesVilles", "Foodie", "RuelleAuthentique"],
    suggested_combos: [],
  },
  {
    id: "italie-sorrente-amalfe",
    title: "Italie : Sorrente & Côte Amalfitaine",
    authenticity_badge: "tested_approved",
    content_slug: "italie",
    summary: "Falaises escarpées, citronniers, cités perchées et douceur méditerranéenne face à la mer.",
    hero_image: "https://...",
    filters: {
      distance: ["europe"],
      climate: ["chaleur", "douceur"],
      transport: ["transports_possibles", "voiture_necessaire"],
      sport_level: ["actif", "tranquille"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["confort", "premium"],
    },
    scores: { repos: 4, exploration: 5, gastronomie: 5, nature_plage: 4, effervescence_urbaine: 3, rythme: 2 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["BordDeMer", "SoleilDouceur", "Foodie", "SlowLife"],
    suggested_combos: [],
  },
  {
    id: "italie-pouilles",
    title: "Italie : Les Pouilles (Bari)",
    authenticity_badge: "tested_approved",
    content_slug: "italie",
    summary: "Eaux turquoises, ruelles blanchies à la chaux, trulli et gastronomie authentique du Sud.",
    hero_image: "https://...",
    filters: {
      distance: ["europe"],
      climate: ["chaleur"],
      transport: ["voiture_necessaire"],
      sport_level: ["tranquille"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 5, exploration: 4, gastronomie: 5, nature_plage: 4, effervescence_urbaine: 2, rythme: 1 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["BordDeMer", "Foodie", "RuelleAuthentique", "SlowLife"],
    suggested_combos: [],
  },
  {
    id: "montreal",
    title: "Montréal",
    authenticity_badge: "tested_approved",
    content_slug: "montreal",
    summary:
      "Vivre Montréal au rythme des 4 saisons — ruelles verdoyantes en été, couleurs de l'automne, Mont-Royal et froid extrême de l'hiver.",
    hero_image: "https://...",
    filters: {
      distance: ["long_courrier"],
      climate: ["chaleur", "douceur", "hiver_cosy"],
      transport: ["sans_voiture", "transports_possibles", "voiture_necessaire"],
      sport_level: ["actif"],
      duration: ["semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 4, exploration: 5, gastronomie: 4, nature_plage: 5, effervescence_urbaine: 4, rythme: 3 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["GrandesVilles", "HiverCosy", "EspacesSauvages", "Foodie"],
    suggested_combos: [
      {
        id: "combo-montreal-nyc",
        target_destination_id: "new-york",
        title: "Extension Ville : New York",
        vibe_type: "Effervescence urbaine & énergie new-yorkaise",
        description:
          "Après le calme et le froid de Montréal, direction New York pour un contraste total — Manhattan, Brooklyn et Central Park.",
        transition_logistics: {
          transport_mode: "Avion, voiture ou bus",
          recommended_days: "3 à 4 jours sur place",
          practical_tip:
            "L'agence Vacances Dragon propose des forfaits pas chers avec hébergement en dehors de la ville mais transfert quotidien inclus — rapport qualité-prix imbattable.",
          partner_link: "https://vacancesdragon.com/fr",
          partner_link_label: "Voir les forfaits Vacances Dragon →",
        },
        min_duration_required: "semaine",
      },
    ],
  },
  {
    id: "new-york",
    title: "New York",
    authenticity_badge: "tested_approved",
    content_slug: "new-york",
    summary:
      "Six voyages, mille facettes — l'énergie brute de Manhattan, la vibe de Brooklyn, Central Park et la magie de la ville en hiver.",
    hero_image: "https://...",
    filters: {
      distance: ["long_courrier"],
      climate: ["douceur", "hiver_cosy", "chaleur"],
      transport: ["sans_voiture", "transports_possibles"],
      sport_level: ["actif"],
      duration: ["semaine", "grand_voyage"],
      budget: ["confort", "premium"],
    },
    scores: { repos: 4, exploration: 5, gastronomie: 5, nature_plage: 2, effervescence_urbaine: 5, rythme: 5 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["GrandesVilles", "Foodie", "HiverCosy", "SoleilDouceur"],
    suggested_combos: [
      {
        id: "combo-nyc-montreal",
        target_destination_id: "montreal",
        title: "Extension Nature : Montréal",
        vibe_type: "Grands espaces & lâcher-prise québécois",
        description:
          "Après l'énergie de New York, une extension à Montréal pour respirer — Mont-Royal, ruelles verdoyantes ou froid extrême selon la saison.",
        transition_logistics: {
          transport_mode: "Vol direct (1h30) ou train Amtrak (10h)",
          recommended_days: "3 à 4 jours sur place",
          practical_tip: "Prendre le vol du matin pour profiter de l'après-midi au Mont-Royal.",
        },
        min_duration_required: "semaine",
      },
    ],
  },
  {
    id: "crete",
    title: "Crète",
    authenticity_badge: "tested_approved",
    content_slug: "crete",
    summary: "Agios Nikolaos, la baie de Mirabello, et une eau d'un bleu qu'on n'attendait pas.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/crete/hero-eau-turquoise.jpg",
    filters: {
      distance: ["europe"],
      climate: ["chaleur", "douceur"],
      transport: ["voiture_necessaire"],
      sport_level: ["tranquille", "actif"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 5, exploration: 4, gastronomie: 4, nature_plage: 5, effervescence_urbaine: 2, rythme: 1 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["BordDeMer", "SoleilDouceur", "Authentique", "SlowLife"],
    suggested_combos: [],
  },
  {
    id: "japon",
    title: "Japon",
    authenticity_badge: "tested_approved",
    content_slug: "japon",
    summary: "Osaka, ses rues et sa décontraction — puis une côte où plus rien ne bouge.",
    hero_image: "https://files.catbox.moe/xwua06.jpg",
    filters: {
      distance: ["long_courrier"],
      climate: ["chaleur", "douceur", "hiver_cosy"],
      transport: ["transports_possibles"],
      sport_level: ["actif"],
      duration: ["semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 5, exploration: 5, gastronomie: 5, nature_plage: 5, effervescence_urbaine: 5, rythme: 5 },
    logistics: {
      solo: true,
      duo: true,
      friends: true,
      family_kids_under_6: true, // testé à 4 ans avec succès
      family_kids_over_6: true,
    },
    tags: ["GrandesVilles", "Foodie", "Authentique", "SlowLife"],
    suggested_combos: [],
  },
  {
    id: "mykonos",
    title: "Mykonos",
    authenticity_badge: "tested_approved",
    content_slug: "mykonos",
    summary:
      "Quatre jours entre copines en juin — plages, ruelles blanches et moulins au coucher du soleil.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/mykonos/web-IMG_20260628_111432.jpg",
    filters: {
      distance: ["europe"],
      climate: ["chaleur"],
      transport: ["voiture_necessaire"],
      sport_level: ["tranquille"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["confort", "premium"],
    },
    scores: { repos: 5, exploration: 5, gastronomie: 4, nature_plage: 4, effervescence_urbaine: 2, rythme: 1 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: false, family_kids_over_6: true },
    tags: ["BordDeMer", "SoleilDouceur", "EntreAmies", "SlowLife"],
    suggested_combos: [],
  },
  {
    id: "dubai",
    title: "Dubaï",
    authenticity_badge: "tested_approved",
    content_slug: "dubai",
    summary: "Gratte-ciel, plages et vieux quartier — le grand écart entre skyline et Al Fahidi.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/dubai/web-IMG_1047.jpg",
    filters: {
      distance: ["long_courrier"],
      climate: ["chaleur"],
      transport: ["transports_possibles", "voiture_necessaire"],
      sport_level: ["tranquille"],
      duration: ["semaine", "grand_voyage"],
      budget: ["confort", "premium"],
    },
    scores: { repos: 4, exploration: 5, gastronomie: 4, nature_plage: 2, effervescence_urbaine: 5, rythme: 1 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["GrandesVilles", "Luxe", "GrandEcart"],
    suggested_combos: [],
  },
  {
    id: "cote-basque",
    title: "Côte Basque",
    authenticity_badge: "tested_approved",
    content_slug: "cote-basque",
    summary:
      "Biarritz, Saint-Jean-de-Luz — surf, couchers de soleil et gâteau basque, en attendant Cap Breton, Seignosse et Hossegor.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/biarritz/web-IMG_20260429_210725.jpg",
    filters: {
      distance: ["proche"],
      climate: ["chaleur", "douceur"],
      transport: ["sans_voiture", "voiture_necessaire", "transports_possibles"],
      sport_level: ["tranquille", "actif"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 5, exploration: 4, gastronomie: 5, nature_plage: 4, effervescence_urbaine: 2, rythme: 1 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["BordDeMer", "Surf", "Foodie", "SoleilDouceur"],
    suggested_combos: [],
  },
  {
    id: "lisbonne",
    title: "Lisbonne",
    authenticity_badge: "tested_approved",
    content_slug: "lisbonne",
    summary: "Collines, azulejos et lumière atlantique — Lisbonne et une excursion à Sintra.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/lisbonne/web-IMG_9475.jpg",
    filters: {
      distance: ["europe"],
      climate: ["chaleur", "douceur"],
      transport: ["sans_voiture", "transports_possibles"],
      sport_level: ["actif"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 4, exploration: 4, gastronomie: 3, nature_plage: 2, effervescence_urbaine: 3, rythme: 2 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["GrandesVilles", "Authentique", "Foodie"],
    suggested_combos: [],
  },
  {
    id: "porto",
    title: "Porto",
    authenticity_badge: "tested_approved",
    content_slug: "porto",
    summary: "Toits en tuile, ruelles escarpées et la Douro en contrebas — l'autre grande ville du Portugal.",
    hero_image: "https://p65bp5tzcfivkgmn.public.blob.vercel-storage.com/porto/web-IMG_20231026_152531.jpg",
    filters: {
      distance: ["europe"],
      climate: ["douceur", "chaleur"],
      transport: ["sans_voiture", "transports_possibles"],
      sport_level: ["actif"],
      duration: ["week_end", "semaine", "grand_voyage"],
      budget: ["eco", "confort", "premium"],
    },
    scores: { repos: 4, exploration: 4, gastronomie: 5, nature_plage: 3, effervescence_urbaine: 3, rythme: 3 },
    logistics: { solo: true, duo: true, friends: true, family_kids_under_6: true, family_kids_over_6: true },
    tags: ["GrandesVilles", "Authentique", "Foodie"],
    suggested_combos: [],
  },
];
